### ISSUE TITLE
Youtube video embed

### ISSUE THREAD

**Issue by link-ding** [alx-plugins/media-extended#12]
Can you show me a example how to embed youtube video?
![image](https://user-images.githubusercontent.com/49264539/114801248-b16ddd80-9dde-11eb-8e4b-492f36482de5.png)
![image](https://user-images.githubusercontent.com/49264539/114801253-b6329180-9dde-11eb-8e28-ab7aa0a88e28.png)

**Comment by okerivy** [comment]
Mine doesn't show up either.
```
![](https://www.youtube.com/watch?v=jNQXAC9IVRw)
```



![image](https://user-images.githubusercontent.com/4578474/116783069-5404ac80-aabf-11eb-93bf-67abe6c22b0d.png)
