### ISSUE TITLE
Wrap links with embed syntax by keyboard shortcut

### ISSUE THREAD

**Issue by kristofferR** [alx-plugins/media-extended#16]
It's slightly annoying that you need to write `![]()` around links after pasting them.

It would be really useful if you could paste media links with a specific shortcut (ctrl+alt+v for example) to automatically turn just the plain URL from your clipboard into `![](URL)` automatically while pasting.

You should also be able to automatically convert plain links into embed links by highlighting them and using a special keyboard shortcut.

This would make adding media from various sites much faster than the current way!

**Comment by kristofferR** [comment]
Probably useful code here: https://github.com/argenos/hotkeysplus-obsidian

**Comment by AidenLx** [comment]
This may be the thing you need: <https://github.com/denolehov/obsidian-url-into-selection>

**Comment by kristofferR** [comment]
That's quite close, but it doesn't add a ! in front.

I just want to copy a Youtube URL from my browser and paste it as an embed link in 1 second into Obsidian, without having any text selected before.

I've created an issue there to request the functionality here: 
https://github.com/denolehov/obsidian-url-into-selection/issues/13
