### ISSUE TITLE
Internal timestamp link not working with mp3

### ISSUE THREAD

**Issue by DaveyUS** [alx-plugins/media-extended#20]
- Clicking the link will open the mp3 in a new pane, and will not start playing. If manually hitting play, it starts only from 0:00.
- Embedded mp3s work perfectly with timestamps
- Embedded or non-embedded mp4s work perfectly

If you are not able to reproduce, I would be happy to help troubleshoot. PM on discord (Davey#5569).

**Comment by FeiLZX3Km** [comment]
同样，插件直接提示不支持screenshot
![image](https://github.com/PKM-er/media-extended/assets/21981195/3f8f5d22-add7-4d6d-a133-4df9bd7be990)

**Comment by FeiLZX3Km** [comment]
> 你文件是视频吗，音频没有截屏的选项啊
> 
> https://mx.pkmer.net/getting-started/first-note#taking-notes

我之前可以“截屏”的音频文件是m4a格式的，现在换成mp3格式的却不能“截屏”了。

**Comment by aidenlx** [comment]
新版本的音频已经不会出现截屏按钮了
