### ISSUE TITLE
🐬Can this plug-in realize the time stamp jump?

### ISSUE THREAD

**Issue by okerivy** [alx-plugins/media-extended#22]
Now I can display a video directly through such code.
```
![](https://www.youtube.com/watch?v=jNQXAC9IVRw#t=10,13)
```
But if I want to set multiple timestamps like youtube, after clicking, refresh the video and jump to the corresponding time. What should I do? 

![image](https://user-images.githubusercontent.com/4578474/116784337-53bbdf80-aac6-11eb-98e7-3f5d33808003.png)

https://forum.obsidian.md/t/link-to-timestamp-of-embedded-audio/7122/9

**Comment by AidenLx** [comment]
It's not yet supported, which is tracked in #14.
