### ISSUE TITLE
Feature: Support Video Speed Control

### ISSUE THREAD

**Issue by Quorafind** [alx-plugins/media-extended#25]
Don't know if it is doable that control video speed by using HTML 5 api:

https://github.com/igrigorik/videospeed#faster-html5-video

If it is doable, please consider to add it to todolist!

**Comment by AidenLx** [comment]
It's supported in Plyr already, which is available in YouTube and Vimeo video now. So it Will be added to local video when this is closed, also Bilibili when this is merged.
