### ISSUE TITLE
no player options shown? or are corrupt

### ISSUE THREAD

**Issue by denemier** [alx-plugins/media-extended#26]
hey i dont have full screen and goto link option, and timeline bars are corrupt,
- i have disabled all other plugins,
- default theme and relaunched the app multiple times
- and still not working like your demo video in the readme
![image](https://user-images.githubusercontent.com/63566495/118387089-d3988c80-b624-11eb-9b73-cc0eaf97eaa8.png)

**Comment by AidenLx** [comment]
I've fixed the slider thumb and full-screen button, but what exactly do you mean by "goto link option"?

**Comment by denemier** [comment]
![2021](https://user-images.githubusercontent.com/63566495/118405840-53a10f80-b682-11eb-9abb-f57f7560c37d.jpg)
yes i confirm the slider thumb is fixed now,
only 2 buttons are missing like in image (taken from demo video)
- goto link style "pip"
- and full screen button

**Comment by AidenLx** [comment]
It's enabled in v2.5.3, and the feature to show or hide options is tracked in #27

**Comment by denemier** [comment]
yes i can double click for full screen, i guess full screen button is planned in #27
