### ISSUE TITLE
Feature request: Youtube iframe embed time control

### ISSUE THREAD

**Issue by link-ding** [alx-plugins/media-extended#3]
Hi, thanks for creating this amazing plugin. I have some idea to imporve this plugin.
Youtube iframe have the API can control the embed video. I have already made some stuff for my self which can read all the timestamp in the obsidina note and open a html page in browser. In html page it chagne the timestamp to button which can go to specific time of the video. Cos I do not know how to do this in obsidian until I find your plugin. I hope you can integrate this function in your plugin.

Here is how the Youtube iframe API work:
js to control the Youtube
```
var player,
    time_update_interval = 0;

function onYouTubeIframeAPIReady() {
    player = new YT.Player('video-placeholder', {
        width: 1200,
        height: 800,
        videoId: 'pQN-pnXPaVg',
        playerVars: {'rel': 0},
        events: {
            onReady: initialize
        }
    });
}

function initialize(){
    clearInterval(time_update_interval);
}

function seek(x) {
    player.seekTo(x);
}

player.seek();
```
In html file
```
<button class="button" onclick="seek(260)">04:20</button> <div>Intro</div>
<script src="https://www.youtube.com/iframe_api"></script>
```
Hope this can give you enough information to do it.

**Comment by AidenLx** [comment]
OK,I'll consider include this feature after the code review from obsidian officials is completed and [pull request](https://github.com/obsidianmd/obsidian-releases/pull/235) is merged

**Comment by AidenLx** [comment]
Done in [v2.1.0](https://github.com/alx-plugins/media-extended/releases/tag/2.1.0)
