### ISSUE TITLE
Feature: Default Setting

### ISSUE THREAD

**Issue by iris2jane** [alx-plugins/media-extended#34]
Can a regular playback path like this be embedded in the page by default?
![image](https://user-images.githubusercontent.com/36763930/119301567-447b1c80-bc95-11eb-8035-5fcdebade055.png)

I guess a special field can trigger this default setting, such as "type: Resources".

**Comment by AidenLx** [comment]
Defining shorthands in frontmatter is proposed in #10, and when it is implemented, you should be able to achieve this with templates.
