### ISSUE TITLE
Request: Fluid width embeds

### ISSUE THREAD

**Issue by NeighNeighNeigh** [alx-plugins/media-extended#5]
Please consider implementing fluid width embeds so that embeded video nicely fits the document width. Heres [a few examples](https://css-tricks.com/fluid-width-video/) of how this can be achieved, including a [vanilla javascript version](https://css-tricks.com/fluid-width-video/#plain-javascript-instead)

PS> thanks for the great plugin. #Loop feature makes me so happy :)

**Comment by AidenLx** [comment]
merged to #11
